# Generated by Django 2.1.1 on 2018-10-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alias',
            field=models.CharField(default=1, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
