# Generated by Django 2.1.1 on 2018-10-01 19:33

from django.db import migrations

CATEGORIES_DATA = [
    {'title': 'exlusive'}
]


def create_default_categories(apps, schema_editor):
    Category = apps.get_model('mainapp', 'Category')

    for data in CATEGORIES_DATA:
        Category.objects.get_or_create(**data)


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product_alias'),
    ]

    operations = [
        migrations.RunPython(
            create_default_categories,
            lambda x, y: (x, y)
        )
    ]



