# Generated by Django 2.1.1 on 2018-10-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='snippet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
